### ISSUE TITLE
cleanup warnings in uboot code

### ISSUE THREAD

**Issue by fambon** [fambon/hkb-gw-v2#2]
./build_u-boot.sh produces warnings when compiling the following files:

arch/arm/cpu/armv7/mx5/soc.c
arch/arm/cpu/armv7/mx5/clock.c
board/hikob/mx50gw2/mx50gw2.c
arch/arm/include/asm/arch/crm_regs.h

**Comment by lglasser** [comment]
all warnings fixed (also fixed one in scripts/kconfig/menu.c)
