### ISSUE TITLE
Test loading of SPL + u-boot using sbloader.exe (Windows)

### ISSUE THREAD

**Issue by fambon** [fambon/hkb-gw-v2#3]
SPL + u-boot now load directly from the SD on the evaluation kit.
- [ ] check that loading from usb using sbloader.exe (Windows) works
- [ ] minimal howto documentation

**Comment by lglasser** [comment]
Feature implemented in commit 1bf275f1fe7cd26450ae6c142a3c131cb44dc172
Mini how to:
- compile SPL + u-boot with configuration option CONFIG_SPL_RAM_DEVICE enabled in mx50gw2.h
- remove SD card or configure boot options to bypass SD Card/eMMC boot
- power on the board, connect USB to PC
- run following commands from Windows PC:
        sb_loader -nojump /f SPL
        sb_loader -nojump -trans 0x77800000 /f u-boot.bin
        sb_loader -exec 0xF8007000
- SPL and u-boot are executed (cf console on UART2)
